package dev.rinstel.genie_tts.inference

import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.sin

@RunWith(AndroidJUnit4::class)
class ReferenceAudioResamplerInstrumentedTest {
    @Test
    fun downsampleMatchesSoxrBoundaryAndDurationWithinTolerance() {
        val input = FloatArray(257)
        input[0] = 1.0f

        val output = ReferenceAudioResampler.resample(input, 32_000, 16_000)

        assertEquals(129, output.size)
        // Compact HQ fixture samples generated by tests/parity/generate_resampler_fixtures.py.
        assertTrue(kotlin.math.abs(output[0] - 0.47843587f) < 0.014f)
        assertTrue(kotlin.math.abs(output[1] - 0.02148393f) < 0.014f)
        assertTrue(output.all { it.isFinite() })
    }

    @Test
    fun downsampleMatchesSoxrFixtureAnchorsAcrossSignalTypes() {
        val sweep = FloatArray(513) { index ->
            sin(40.0 * PI * index / 512.0).toFloat()
        }
        val sweepOutput = ReferenceAudioResampler.resample(sweep, 32_000, 16_000)
        assertEquals(257, sweepOutput.size)
        assertClose(sweepOutput[0], 0.042268168f, 0.001f)
        assertClose(sweepOutput[1], 0.462894917f, 0.001f)
        assertClose(sweepOutput[128], 0.0f, 0.0001f)
        assertClose(sweepOutput[256], -0.042268217f, 0.001f)

        val speechLike = FloatArray(401) { index ->
            val position = index / 400.0
            (0.55 * sin(13.0 * PI * position) + 0.2 * sin(71.0 * PI * position)).toFloat()
        }
        val speechOutput = ReferenceAudioResampler.resample(speechLike, 32_000, 16_000)
        assertEquals(201, speechOutput.size)
        assertClose(speechOutput[0], 0.029738743f, 0.001f)
        assertClose(speechOutput[1], 0.284872353f, 0.001f)
        assertClose(speechOutput[100], 0.350000024f, 0.001f)
        assertClose(speechOutput[200], 0.029738756f, 0.001f)

        val edgeLength = FloatArray(1001) { index -> index / 1001.0f }
        val edgeOutput = ReferenceAudioResampler.resample(edgeLength, 32_000, 16_000)
        assertEquals(501, edgeOutput.size)
        assertClose(edgeOutput[0], 0.000170194f, 0.0001f)
        assertClose(edgeOutput[250], 0.499500513f, 0.0001f)
        assertClose(edgeOutput[500], 0.738309324f, 0.002f)
    }

    private fun assertClose(actual: Float, expected: Float, tolerance: Float) {
        assertTrue("$actual is not within $tolerance of $expected", abs(actual - expected) <= tolerance)
    }
}
